"""add columns in user model

Revision ID: 754a97ba00ac
Revises: 356e4b7e1d2d
Create Date: 2020-01-11 18:18:01.153218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754a97ba00ac'
down_revision = '356e4b7e1d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
